"""
Django settings for virtuwork_pro project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%_othfsz5c(bzb%rhyx!@u4vaz+$295x89mxgquf_+^%vf)dv@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'agents',
    'simulation',
    'evaluation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'virtuwork_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'virtuwork_pro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'virtuwork',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
OPENROUTER_API_KEYS = [
    "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",
    "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",
    "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",
    "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",
    "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",
    "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",
    
    "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",
    "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",
    "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",
    "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",
    "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",
    "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"
    ]