# Generated by Django 5.0 on 2026-02-10 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_task_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='education',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='soft_skills_data',
            field=models.JSONField(default=dict, help_text='Stores rolling averages for Professionalism, Clarity, and Confidence'),
        ),
    ]
