# Generated by Django 5.0 on 2026-02-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0007_simulation_education_simulation_soft_skills_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_file_extension',
            field=models.CharField(blank=True, help_text='Expected file type (e.g., .py, .csv, .txt)', max_length=10, null=True),
        ),
    ]
